### ISSUE TITLE
Device Support

### ISSUE THREAD

**Issue by RossComputerGuy** [shidel/FDNET#1]
I have a computer running Freedos and I'd like to have drivers for the network adapter(s). I have a list of the adapters.

- https://pci-ids.ucw.cz/read/PC/10ec/5289
- https://pci-ids.ucw.cz/read/PC/1814/5390
- https://pci-ids.ucw.cz/read/PC/10ec/8168

**Comment by shidel** [comment]
Hello,

Unfortunately, the there only a few known open source networking drivers available for DOS at present. Although the _**RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller**_ seems like a rather common NIC, it is currently outside of the support provided by _FDNET_. Have you tried consulting the [_**freedos-user**_ ](http://www.freedos.org/lists/)mailing list? There are many users that frequent the list that may have knowledge of a freely available DOS packet driver and how to configure it for you laptop. I hope you can find a solution to this issue. If you do, it may be something that could be included in future releases of the _FDNET_ package. I'm sorry I could not be of further help at this time.
