### ISSUE TITLE
How to run multiple concurrent networked applications?

### ISSUE THREAD

**Issue by mcandre** [shidel/FDNET#2]
Hi,

I am working on setting up a portable Vagrant base box for FreeDOS, as a convenient way for enthusiasts to boot and provision DOS virtual machines. Thanks to FDNET, I am able to do a lot of cool things in DOS, including downloading HTTP files with wget. Good to know that the retro community is still thriving!

The next step in getting the Vagrant box prepared for more complex operations, is to install some kind of sshd or telnet server, so that the user can execute commands on the DOS guest in an automated fashion, via CLI tools rather than having to use the VirtualBox GUI.

While there are some telnet servers available for DOS, such as rmenu, these only sorta-kinda work. rmenu frequently drops user signals, making it difficult to reliably execute commands over telnet. What's more, the COMMAND.COM shell available in rmenu somehow breaks other applications. So while `wget` works okay from a top-level COMMAND.COM session, the same command fails to connect when run from rmenu over telnet.

I'm writing to you to clarify something: Is this behavior a particular glitch with rmenu? Can you provide an example configuration for how to setup a telnet server for FreeDOS that is able to successfully run other networked programs (`wget`, `ping`, `htget`, `dhcp`, etc.)?

Could this be a flaw with the particular TCP/IP stack that I am using, mTCP? Does WATTCP fair any better? And finally, could this be a flaw in FDNET, where other packet drivers may not have this problem? Or, I fear, is this a limitation in FreeDOS, where only one application may bind network ports at any given time?

**Comment by shidel** [comment]
FDNet is only a simple script to facilitate network support on a limited set of hardware it can recognize. Mostly, that is the simulated hardware provided by **_VMware, VirtualBOX and QEMU_**. If it can identify the hardware, it loads the appropriate vendor specific packet driver and configures DHCP. 

Unfortunately, your question is far beyond the scope of FDNet's goals. I recommend asking posting you questions to the FreeDOS user and/or developer mailing list. The individuals there are very knowledgeable and may be able to assist you in achieving your end goals. You can find the mailing lists through the official FreeDOS website at [http://www.freedos.org/forums/](http://www.freedos.org/forums/).
